apiVersion: apps/v1
kind: Deployment
metadata:
  name: nguti-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nguti-app
  template:
    metadata:
      labels:
        app: nguti-app
    spec:
      containers:
      - name: nguti-app
        image: ekangaki/nguti-docker:v1
        ports:
        - containerPort: 3000
